version: '3.3'

services:
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: db
    restart: always
    env_file: .env
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp_network

  php-fpm:
    build: 
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-php:7.4-fpm}      
    container_name: php-fpm    
    volumes:
      - ${wp_volume}:/var/www/html 
    depends_on:
      - db
    networks:
      - wp_network
    restart: always

  nginx:
    depends_on:
      - php-fpm
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ${wp_volume}:/var/www/html      
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wp_network
    links:
      - php-fpm

volumes:
  dbdata:

networks:
  wp_network:
    driver: bridge 