version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file: .env
    volumes: 
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  php:
    depends_on: 
      - db
    build:
      context: ./php-fpm
    container_name: php
    restart: always
    # env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - php
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8081:8080
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge 