version: '3.3'

services:
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: db
    restart: always
    env_file: .env
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wp:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm}
    container_name: wp
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-db}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-wordpress}
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  nginx:
    depends_on:
      - wp
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./wordpress:/var/www/html      
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    links:
      - wp

  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8081:8080
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge 