---
- name: Ansible deploy wordpress with docker
  hosts: localhost
  gather_facts: no

  vars_files:
    - env.yml

  tasks:
  - name: download latest version of wordpress
    shell: ./install_local.sh

  - name: Create a network for containers
    docker_network:
      name: "{{ docker_network }}"


  - name: Create if not exist volume dbdata
    docker_volume:
        name: "{{ db_volume }}"


  - name: Launch database container
    docker_container:
      name: "{{ db_name }}"
      image: mysql:{{ MYSQL_VERSION }}
      restart: yes
      detach: yes
      state: started 
      env:
        MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
        MYSQL_USER: "{{ MYSQL_USER }}"
        MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
        MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"      
      volumes:
        - "{{ db_volume }}:/var/lib/mysql"
      command: --default-authentication-plugin=mysql_native_password
      network_mode: "{{ docker_network }}"     
       
  
  - name: Create php image
    docker_image:
      name: "{{ php_name }}"
      source: build
      build:  
        path: ./php
        args:
          PHP_VERSION: "{{ PHP_VERSION }}"
      force_source: yes
  
  - name: Launch php container
    docker_container:
      name: "{{ php_name }}"
      image: "{{ php_name }}"
      restart: yes      
      volumes:
        - "{{ wp_volume }}:/var/www/html" 
      network_mode: "{{ docker_network }}" 
      state: started

  - name: Launch nginx container
    docker_container:
      name: "{{ nginx_name }}"
      image: nginx:{{ NGINX_VERSION }}
      restart: yes
      volumes:
        - "{{ wp_volume }}:/var/www/html"
        - "./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf"       
      ports:
        - "8082:80"
      links:
        - "{{ php_name }}"
      network_mode: "{{ docker_network }}"
      state: started
